name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "6 20 * * 6"

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Gems cache
        uses: actions/cache@v3
        with:
          path: ~/gems
          key: gems-3.2-${{ hashFiles('*.gemspec', 'Gemfile') }}
          restore-keys: |
            gems-3.2-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3
      - name: Check code style
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "head"
          - "jruby-9.3"
          - "jruby-9.4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Gems cache
        uses: actions/cache@v3
        with:
          path: ~/gems
          key: gems-${{ matrix.ruby }}-${{ hashFiles('*.gemspec', 'Gemfile') }}
          restore-keys: |
            gems-${{ matrix.ruby }}-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake spec
